#
# Hiera defaults.yaml
#
# This is intended for configuration relevant to *any* node. 
# Specialized configuration at build-time should go in local.yaml
#

classes:
  - myclass

myclass::str_something: 'myclass-string-val'
